from flask import Flask, jsonify
import random

app = Flask(__name__)


truth = [
    "Did you ever drink before you were of the legal drinking age?",
    "What is the craziest thing you have done while under the influence of alcohol?",
    "What was the last thing you searched for on your phone web browser?",
    "If you had to choose between going naked or having your thoughts appear in thought bubbles above your head for everyon to read, which would you choose?",
    "Have you ever walked in on your parents doing it?",
    "After you've dropped a piece of food, what's the longest time you've left in on the ground and then ate it?",
    "Have you ever tasted a booger?",
    "What's the first thing you would do if you woke up one day as the opposite sex?",
    "If someone heard you snoring, would they say it's obnoxiously loud?",
    "Have you ever peed in a pool full of people?",
    "Who do you think is the worst dressed person in this room?",
    "Have you ever farted in an elevator?",
    "Have you ever played Cards Against Humanity with your parents?"
    "True or False? You have a crush on an elderly person?",
    "What is the largest amount of food you've eaten in ine sitting?",
    "Of the people in this room, who do you want to trade lives with for one day?",
    "What are some things you think about when sitting on the toilet?",
    "What is the most embarrassing situation you’ve ever been a part of?",
    "Did you have an imaginary friend growing up?",
    "Do you cover your eyes during a scary part in a movie?",
    "Have you ever practiced kissing in a mirror?",
    "What, if any, sport do you absolutely hate against popular opinion?",
    "Did your parents ever give you the “birds and the bees” talk?",
    "What is your guilty pleasure that you never tell anyone?",
    "What is your worst or most embarrassing habit?",
    "Has anyone ever walked in on you when taking a dump in the bathroom?",
    "Have you ever had a major wardrobe malfunction while in public?",
    "Have you ever accidentally walked into a wall or building?",
    "Do you pick your nose when you’re alone?",
    "How much older of an individual would you enter a relationship with?",
    "Do you pee in the shower?",
    "Have you ever peed yourself at school before?",
    "What was your most embarrassing moment in public?",
    "Have you ever farted loudly in class or another social setting?",
    "Do you ever talk to yourself in the mirror?",
    "What is your guilty pleasure?",
    "You’re in a public restroom and just pooped, then you realized your stall has no toilet paper. What do you do?",
    "What would be in your web history that you’d be embarrassed if someone saw?",
    "Have you ever tried to take a sexy or naked picture of yourself?",
    "Do you sleep with a stuffed animal or something else for comfort?",
    "Do you drool in your sleep?",
    "Do you talk in your sleep?",
    "Who are you secretly attracted to?",
    "Do you think kittens are cute?",
    "Who do you like the least in this room and why?",
    "What does your dream boy or girl look like?",
    "What is your go-to song for the shower?",
    "Who is the sexiest person in this room?",
    "How would you rate your looks on a scale of 1 to 10?",
    "Would you rather have sex with [insert name] in secret or not have sex with that person but everyone thinks you did?",
    "What things do you not like about me?",
    "What color and kind of underwear are you wearing right now?",
    "What song do you enjoy in privacy?",
    "What was the last thing you texted someone of the opposite sex?",
    "If you were rescuing people from a burning building and you had to leave one person behind from this room, who would it be?",
    "Have you ever accidentally revealed a friends secret?",
    "Do you think that you and your current girlfriend or boyfriend will ever be married?",
    "How often do you wash your undergarments?",
    "Have you ever tasted ear wax?",
    "Have you ever farted and then blamed someone else?",
    "Have you ever tasted your sweat?",
    "What is the most illegal thing you’ve ever done?",
    "Who is your favorite person in you immediate family?",
    "Would you trade your sibling in for a million dollars if there were no other consequences?",
    "Would you trade in your dog for a million dollars?",
    "What is your biggest pet peeve that other people do?",
    "If you were to join the military what job do you think you’d enjoy the most ?",
    "If you were allowed to marry more than one person, would you? Who would you choose to marry?",
    "Would you rather lose your sex organs forever or gain 200 pounds only in your stomach?",
    "Would you choose to save 100 people without anyone knowing about it or not save them but have everyone praise you for it?",
    "If you could only hear one song for the rest of your life, what would it be?",
    "If you lost one day of your life every time you said a swear word, would you try not to do it?",
    "Who in this room would be the worst person to date? Why?",
    "Would you rather live with no internet or no A/C or heating?",
    "What was your favorite childhood video game?",
    "If someone offered you $1 million dollars to break up with your girlfriend/boyfriend, would you do it?",
    "If you were reborn, what decade would you want to be born in?",
    "If you could go back in time in erase one thing you said or did, what would it be?",
    "Has your boyfriend or girlfriend ever embarrassed you?",
    "Have you ever thought about cheating on your partner?",
    "If you could suddenly become invisible, what would you do?",
    "Have you ever been caught checking someone out?",
    "What is your favorite alcoholic beverage?",
    "Have you ever waved at someone thinking they saw you when really they didn’t? What did you do when you realized it?",
    "What’s the longest time you’ve stayed in the bathroom, and why did you stay for that long?",
    "What’s the most unflattering school picture of you?",
    "Have you ever cried because you missed your parents so much?",
    "Do you prefer a bath or a shower? Why?",
    "Would you rather be caught picking your nose or picking a wedgie?",
    "Describe the strangest dream you’ve ever had. Did you like it?",
    "Have you ever posted something on social media that you regret?",
    "What is your biggest and most irrational fear?",
    "What is the scariest movie you have ever seen?",
    "Do you sing in the shower?",
    "Have you ever ding dong ditched someone?",
    "What is something you have done that has made you really proud?",
    "The world ends next week and you can do anything you want (even if it’s illegal). What would you do?",
    "Would you wear your shirt inside out for a whole day if someone paid you $100?",
    "What salad dressing could you drink out of the bottle?",
    "What is the most childish thing that you still do?",
    "How far would you go to land the guy or girl of your dreams?",
    "If you had to choose would you rather have a broken arm or a broken leg and why?",
    "Tell us about a time you embarrassed yourself in front of a crush.",
    "Have you ever kept a library book?",
    "Who is one person you pretend to like, but actually don’t?",
    "What children’s movie could you watch over and over again?",
    "Do you have bad foot odor?",
    "Do you have any silly nicknames?",
    "When was the last time you wet the bed?",
    "How many pancakes have you eaten in a single sitting?",
    "Have you ever accidentally hit something with your car?",
    "If you had to make out with any Disney character, who would it be?",
    "Have you ever watched a movie you knew you shouldn’t?",
    "Have you ever wanted to try LARP (Live Action Role-Play)?",
    "What app on your phone do you waste the most time on?",
    "Have you ever pretended to be sick to get out of something? If so, what was it?",
    "What is the most food you’ve eaten in a single sitting?",
    "What is the single most painful experience of your life?",
    "Do you dance when you’re by yourself?",
    "Would you have voted for or against Trump?",
    "What song on the radio do you sing with every time it comes on?",
    "Do you sleep with a stuffed animal?",
    "Do you own a pair of footie pajamas?",
    "What is the meanest thing you’ve ever said to someone?",
    "Are you scared of the dark?",
    "What ‘As seen on TV’ product do you secretly want to buy?",
    "Do you still take bubble baths?",
    "If you were home by yourself all day, what would you do?",
    "How many selfies do you take a day?",
    "Would you date your high school crush today?",
    "What is something you’ve done to try to be ‘cooler’?",
    "When was the last time you brushed your teeth?",
    "How often do you wear the same outfit in a week?",
    "Have you ever used self tanner?",
    "What is your favorite breed of dog?",
    "What do your favorite pajamas look like?",
    "Do you have a security blanket?",
    "Do you still have something you have cherished from childhood?",
    "Have you ever eaten something off the floor?",
    "Have you ever butt-dialed someone?",
    "Do you like hanging out with your parents?",
    "Do you prefer staying up late or going to bed early?",
    "Have you ever got caught doing something you shouldn’t?",
    "What part of your body do you love and which part do you hate?",
    "Have you ever had lice?",
    "Have you ever pooped your pants?",
    "What was the last rate-R movie you watched?",
    "What is your favorite type of ice cream?",
    "Do you lick your plate?",
    "What is something that no one else knows about you?",
    "Have you ever stolen anything?",
    "Do you drool in your sleep?",
    "Who is your secret crush?",
    "What color underwear are you wearing right now?",
    "Who is your favorite? Mom or Dad?"
]

dare = [
    "Let the group choose an item for you to brush your teeth with.",
    "Write your name on the floor with your tongue.",
    "Go outside and pick exactly 40 blades of grass with a pair of tweezers.",
    "Stick a Hot Cheeto in your nose and leave it there for 5 minutes.",
    "Open Facebook, go to the account of the first person you see, and like every post on their wall going back to a year.",
    "Eat a whole piece of paper.",
    "Lick a car tire.",
    "Open your front door and howl like a wolf for 30 seconds.",
    "Let the person to your right put duct tape on any part of your body they choose and rip it off.",
    "I dare you to tie your hands to your ankles for the rest of the game.",
    "Put a bunch of honey on your nose and coat it with flour",
    "Dump a bunch of legos on the floor and walk over it with your bare feet.",
    "Eat a spoonful of mustard.",
    "Jump into a dumpster.",
    "Lift up the couch cushions, and if there is anything under it, you need to put it in your mouth for 10 seconds.",
    "Spin around 10 times and try to walk straight.",
    "Eat a raw egg.",
    "Write a letter to your doctor describing an embarrassing rash you have, and post it on Facebook.",
    "Cover your hair with shaving cream and leave it on until the end of the game.",
    "Let the group choose 3 random things from the refrigerator and mix it together. Then you have to eat it.",
    "Stand up and do jumping jacks until your next turn.",
    "Rub your armpits and then smell your fingers.",
    "Dig through the trash and name everything you find.",
    "Sniff another person’s armpit for 10 seconds.",
    "Give your phone to another person to send a text message to their contact of choice.",
    "Let the other persons go through your phone for a minute.",
    "Allow someone to pour ice down your shirt and pants.",
    "Let another person throw flour in your face.",
    "Sing a song chosen by the group while eating spoonfuls of peanut butter.",
    "Close your eyes and let your friends put whatever food from the fridge they want in your mouth.",
    "One by one, make up a title for each persons’ movie about their life.",
    "Let your friends pose you and stay like that until the next round.",
    "Let each person choose one word, then attempt to form a sentence with it and post it to Facebook.",
    "Empty your purse, backpack, or wallet and let everyone see what you have.",
    "Allow the person to your right to tickle you.",
    "Whoever’s name begins with an A in the group must call your parents and tell them what a bad friend you are to them.",
    "Let each person in the group slap you as hard as they can on your butt.",
    "Do your best impression of someone in the room and keep going until someone correctly guesses who it is.",
    "Eat a raw onion and do your best not to cry.",
    "Be blindfolded and let someone feed you something.",
    "Lick mayonnaise off of someone’s toe.",
    "Someone has to dip their finger in the trash can and you have to lick it.",
    "Go to the bathroom, and the person to your left has to be in there with you the whole time.",
    "Trade socks with the person to your right.",
    "Have the person to your right do 10 squats while you lie underneath them.",
    "Let a person in the group put a leash on you and walk you down the street.",
    "Hold hands with the person to you left for the rest of the game.",
    "Hand your phone to the person across from you and let them post whatever they want to your social media accounts.",
    "Smells someone else’s shoes",
    "Take the socks off the person’s feet across from you and wear them like gloves until your next turn.",
    "Serenade the person next to you.",
    "Take a selfie with the person next to you, and post it on social media along with a deep and emotional paragraph about what they mean to you.",
    "Let the person across from you give you a wedgie.",
    "Dance aggressively until you run out of breath.",
    "Eat a single spaghetti like in Lady and the Tramp with the person to your left.",
    "Get a bar of soap from the bathroom and sell it to the group for 3 minutes.",
    "Go outside, and while skipping down the street, sing “Let it Go’ from Frozen.",
    "With your eyes closed, pick someone from your contact list and send them a text.",
    "Stand up and do your best impersonation of the person on your right.",
    "Go in the kitchen and rearrange everything in the food pantry in alphabetical order.",
    "Imagine the person to your left is your pet, talk to them as though you just got home.",
    "Imagine that you are a dog and act like it until your next turn.",
    "Describe what the sky looks like without using the words blue or white.",
    "Sing the chorus of your favorite song.",
    "Everytime someone chooses dare, walk across the floor like a crab and embrace them with a hug.",
    "Make up a song about the host of the party.",
    "Knock on the neighbor’s door and explain to them that your pet penguin got loose and ask if you can look for it in their backyard.",
    "Invent a new color for nail polish and describe the person who would be most likely to wear it.",
    "For the next 15 minutes, everything you say must be spoken in baby talk.",
    "Give 5 dollars to each person if you curse at any point during the game.",
    "Make a sandwich while blindfolded.",
    "Stick an egg in the microwave and attempt to juggle it for 30 seconds.",
    "Eat a spoonful of hot sauce.",
    "From now until your next turn, every time someone talks, interrupt by saying, “that’s a lie.”",
    "You notice that the person sitting on your right has something on their face, spit on your finger and wipe it off for them.",
    "Get down on one knee and propose to the person on your left.",
    "Awkwardly smell someone else’s hair until they notice.",
    "Take the socks off the person’s feet across from you and wear them like gloves until your next turn.",
    "Open Facebook and “like” the first thing that pops up even if you disagree with it.",
    "Stand up and do your best impersonation of your mom.",
    "Go for a short walk outside and while walking, hold a conversation with yourself.",
    "Rearrange all the pictures in the room according to their size.",
    "Take off your shoe and clean your foot as though you are an animal.",
    "Stick your head in the toilet.",
    "Put makeup on the person sitting the farthest away from you.",
    "Do your best impersonation of someone else in the room and keep going until someone else guesses who you are.",
    "Call a realtor and show genuine interest in a random house for several minutes.",
    "For the next 10 minutes, when someone speaks, put your ear up close to them and act as though you can’t hear what they are saying.",
    "Stand up and do jumping jacks until your next turn.",
    "For the rest of the game, you must cluck like a chicken at the beginning and end of everything you say.",
    "Be silent and say nothing from now until your next turn.",
    "While blindfolded, you must eat something that the person to your left chooses to feed you.",
    "Tie your shoe strings together with another person and walk together to the end of the driveway and back.",
    "Stand in the backyard and yell at the top of your lungs, “I was adopted! Nooooooo.”",
    "Text a friend and tell them their hair is on backward.",
    "Wear your clothes backward for the duration of the game.",
    "Tell someone something negative you have said about them in private.",
    "Go outside to the trash bin and throw a tantrum because someone put trash in it.",
    "Go outside and pick exactly 40 blades of grass with a pair of tweezers.",
    "Call someone and confess your new-found love for Justin Bieber.",
    "Kiss the person to your right on the cheek.",
    "Sniff the person to your left and tell them they smell bad.",
    "Rub your armpits and then smell your fingers.",
    "Sit on your hands for the remainder of the game.",
    "Knock on the neighbor’s door and ask if you can park your helicopter in their driveway.",
    "Take someone with you outside in the sight of the neighbors and stare into the sky until someone asks you what you are looking at, then tell them that you saw a UFO.",
    "Text your mom and tell her that you are expecting a baby.",
    "Walk outside frantically carrying an empty leash and approach people asking them if they have seen your pet alligator because it just escaped.",
    "Go into the bathroom and look in the cabinet. Write a short summary of what you find and read it to the group.",
    "Call the nearest gas station and ask them if they sell hemorrhoid cream.",
    "Stop a car that is going down the street and tell them that their wheels are turning.",
    "Make a sandwich containing every condiment in your refrigerator.",
    "Close your eyes and let everyone draw on you for 5 minutes.",
    "Tell a bizarre 2-minute story about the night you slept in the woods.",
    "Stand up and dance the twist until your next turn.",
    "Name the person in the room who you think is the best dressed.",
    "Name the person in the room who you think is the worst dressed.",
    "Text your siblings and tell them that you just found out you are adopted.",
    "Make the sound of a dripping faucet until your next turn.",
    "From now until the end of the game, every time you talk, speak like a robot.",
    "Act like a cheerleader and do a cheer about the host of the party.",
    "For the rest of the game, you must only communicate using animal sounds.",
    "Make confetti out of a tissue.",
    "Describe to the group what your last bathroom experience was like.",
    "Get a magazine and go outside. Roll up the magazine, put it on your nose and act and sound like an elephant.",
    "Make a hat out of aluminum foil then put the hat on and post a selfie to social media. Leave the hat on for the duration of the game.",
    "Hang your socks from your ears until the end of the game.",
    "Fill your mouth with water and act like a fountain.",
    "For the rest of the game you must say your name at the beginning and the end of every sentence you speak.",
    "Repeat everything the person to your left says until your next turn.",
    "Choose one inanimate object that is in the room. Now spend the next 2-minutes telling the group what that object is thinking.",
    "Attempt to lick your elbow for at least five minutes.",
    "Make eye contact with a person and don’t break it until it’s your turn again.",
    "Get a mouthful of water and gargle it until your next turn.",
    "Do the chicken dance to no music until your next turn.",
    "Crack an egg on your head.",
    "Stick out your tongue and talk that way until your next turn.",
    "Bust your best dance move right now.",
    "Turn your pants inside out and wear them.",
    "Do everything with “crab hands” for the rest of the game.",
    "Reenact what you think it is like to give birth.",
    "For the rest of the game, speak like you are the President of America.",
    "Pretend like you are drunk for the rest of the game.",
    "Eat a spoonful of hot sauce.",
    "Make up a short cheer and shout it to the room.",
    "Speak in the voice of your favorite cartoon character until your next turn.",
    "Use ketchup to put the mark of Simba on your forehead.",
    "Put a piece of American cheese on your cheek and leave it until your next turn.",
]

truthordare = [
    "Did you ever drink before you were of the legal drinking age?",
    "What is the craziest thing you have done while under the influence of alcohol?",
    "What was the last thing you searched for on your phone web browser?",
    "If you had to choose between going naked or having your thoughts appear in thought bubbles above your head for everyon to read, which would you choose?",
    "Have you ever walked in on your parents doing it?",
    "After you've dropped a piece of food, what's the longest time you've left in on the ground and then ate it?",
    "Have you ever tasted a booger?",
    "What's the first thing you would do if you woke up one day as the opposite sex?",
    "If someone heard you snoring, would they say it's obnoxiously loud?",
    "Have you ever peed in a pool full of people?",
    "Who do you think is the worst dressed person in this room?",
    "Have you ever farted in an elevator?",
    "Have you ever played Cards Against Humanity with your parents?"
    "True or False? You have a crush on an elderly person?",
    "What is the largest amount of food you've eaten in ine sitting?",
    "Of the people in this room, who do you want to trade lives with for one day?",
    "What are some things you think about when sitting on the toilet?",
    "What is the most embarrassing situation you’ve ever been a part of?",
    "Did you have an imaginary friend growing up?",
    "Do you cover your eyes during a scary part in a movie?",
    "Have you ever practiced kissing in a mirror?",
    "What, if any, sport do you absolutely hate against popular opinion?",
    "Did your parents ever give you the “birds and the bees” talk?",
    "What is your guilty pleasure that you never tell anyone?",
    "What is your worst or most embarrassing habit?",
    "Has anyone ever walked in on you when taking a dump in the bathroom?",
    "Have you ever had a major wardrobe malfunction while in public?",
    "Have you ever accidentally walked into a wall or building?",
    "Do you pick your nose when you’re alone?",
    "How much older of an individual would you enter a relationship with?",
    "Do you pee in the shower?",
    "Have you ever peed yourself at school before?",
    "What was your most embarrassing moment in public?",
    "Have you ever farted loudly in class or another social setting?",
    "Do you ever talk to yourself in the mirror?",
    "What is your guilty pleasure?",
    "You’re in a public restroom and just pooped, then you realized your stall has no toilet paper. What do you do?",
    "What would be in your web history that you’d be embarrassed if someone saw?",
    "Have you ever tried to take a sexy or naked picture of yourself?",
    "Do you sleep with a stuffed animal or something else for comfort?",
    "Do you drool in your sleep?",
    "Do you talk in your sleep?",
    "Who are you secretly attracted to?",
    "Do you think kittens are cute?",
    "Who do you like the least in this room and why?",
    "What does your dream boy or girl look like?",
    "What is your go-to song for the shower?",
    "Who is the sexiest person in this room?",
    "How would you rate your looks on a scale of 1 to 10?",
    "Would you rather have sex with [insert name] in secret or not have sex with that person but everyone thinks you did?",
    "What things do you not like about me?",
    "What color and kind of underwear are you wearing right now?",
    "What song do you enjoy in privacy?",
    "What was the last thing you texted someone of the opposite sex?",
    "If you were rescuing people from a burning building and you had to leave one person behind from this room, who would it be?",
    "Have you ever accidentally revealed a friends secret?",
    "Do you think that you and your current girlfriend or boyfriend will ever be married?",
    "How often do you wash your undergarments?",
    "Have you ever tasted ear wax?",
    "Have you ever farted and then blamed someone else?",
    "Have you ever tasted your sweat?",
    "What is the most illegal thing you’ve ever done?",
    "Who is your favorite person in you immediate family?",
    "Would you trade your sibling in for a million dollars if there were no other consequences?",
    "Would you trade in your dog for a million dollars?",
    "What is your biggest pet peeve that other people do?",
    "If you were to join the military what job do you think you’d enjoy the most ?",
    "If you were allowed to marry more than one person, would you? Who would you choose to marry?",
    "Would you rather lose your sex organs forever or gain 200 pounds only in your stomach?",
    "Would you choose to save 100 people without anyone knowing about it or not save them but have everyone praise you for it?",
    "If you could only hear one song for the rest of your life, what would it be?",
    "If you lost one day of your life every time you said a swear word, would you try not to do it?",
    "Who in this room would be the worst person to date? Why?",
    "Would you rather live with no internet or no A/C or heating?",
    "What was your favorite childhood video game?",
    "If someone offered you $1 million dollars to break up with your girlfriend/boyfriend, would you do it?",
    "If you were reborn, what decade would you want to be born in?",
    "If you could go back in time in erase one thing you said or did, what would it be?",
    "Has your boyfriend or girlfriend ever embarrassed you?",
    "Have you ever thought about cheating on your partner?",
    "If you could suddenly become invisible, what would you do?",
    "Have you ever been caught checking someone out?",
    "What is your favorite alcoholic beverage?",
    "Have you ever waved at someone thinking they saw you when really they didn’t? What did you do when you realized it?",
    "What’s the longest time you’ve stayed in the bathroom, and why did you stay for that long?",
    "What’s the most unflattering school picture of you?",
    "Have you ever cried because you missed your parents so much?",
    "Do you prefer a bath or a shower? Why?",
    "Would you rather be caught picking your nose or picking a wedgie?",
    "Describe the strangest dream you’ve ever had. Did you like it?",
    "Have you ever posted something on social media that you regret?",
    "What is your biggest and most irrational fear?",
    "What is the scariest movie you have ever seen?",
    "Do you sing in the shower?",
    "Have you ever ding dong ditched someone?",
    "What is something you have done that has made you really proud?",
    "The world ends next week and you can do anything you want (even if it’s illegal). What would you do?",
    "Would you wear your shirt inside out for a whole day if someone paid you $100?",
    "What salad dressing could you drink out of the bottle?",
    "What is the most childish thing that you still do?",
    "How far would you go to land the guy or girl of your dreams?",
    "If you had to choose would you rather have a broken arm or a broken leg and why?",
    "Tell us about a time you embarrassed yourself in front of a crush.",
    "Have you ever kept a library book?",
    "Who is one person you pretend to like, but actually don’t?",
    "What children’s movie could you watch over and over again?",
    "Do you have bad foot odor?",
    "Do you have any silly nicknames?",
    "When was the last time you wet the bed?",
    "How many pancakes have you eaten in a single sitting?",
    "Have you ever accidentally hit something with your car?",
    "If you had to make out with any Disney character, who would it be?",
    "Have you ever watched a movie you knew you shouldn’t?",
    "Have you ever wanted to try LARP (Live Action Role-Play)?",
    "What app on your phone do you waste the most time on?",
    "Have you ever pretended to be sick to get out of something? If so, what was it?",
    "What is the most food you’ve eaten in a single sitting?",
    "What is the single most painful experience of your life?",
    "Do you dance when you’re by yourself?",
    "Would you have voted for or against Trump?",
    "What song on the radio do you sing with every time it comes on?",
    "Do you sleep with a stuffed animal?",
    "Do you own a pair of footie pajamas?",
    "What is the meanest thing you’ve ever said to someone?",
    "Are you scared of the dark?",
    "What ‘As seen on TV’ product do you secretly want to buy?",
    "Do you still take bubble baths?",
    "If you were home by yourself all day, what would you do?",
    "How many selfies do you take a day?",
    "Would you date your high school crush today?",
    "What is something you’ve done to try to be ‘cooler’?",
    "When was the last time you brushed your teeth?",
    "How often do you wear the same outfit in a week?",
    "Have you ever used self tanner?",
    "What is your favorite breed of dog?",
    "What do your favorite pajamas look like?",
    "Do you have a security blanket?",
    "Do you still have something you have cherished from childhood?",
    "Have you ever eaten something off the floor?",
    "Have you ever butt-dialed someone?",
    "Do you like hanging out with your parents?",
    "Do you prefer staying up late or going to bed early?",
    "Have you ever got caught doing something you shouldn’t?",
    "What part of your body do you love and which part do you hate?",
    "Have you ever had lice?",
    "Have you ever pooped your pants?",
    "What was the last rate-R movie you watched?",
    "What is your favorite type of ice cream?",
    "Do you lick your plate?",
    "What is something that no one else knows about you?",
    "Have you ever stolen anything?",
    "Do you drool in your sleep?",
    "Who is your secret crush?",
    "What color underwear are you wearing right now?",
    "Who is your favorite? Mom or Dad?",
    "Tell me about the last time you got really embarrassed.",
    "Hum a song of your choice, don’t stop until someone correctly guesses the song.",
    "What’s the longest you’ve worn the same outfit for?",
    "Pour a glass of ice water on your head.",
    "Have you ever had a crush on one of your teachers?",
    "Bite down on both of your pinky fingers for fifteen seconds, then tightly interlock your pinkies.",
    "Where are you ticklish?",
    "Do your best touchdown celebration dance.",
    "What do you think is your best feature?",
    "Go as long as you can without blinking.",
    "Have you ever cheated on a test?",
    "Choose another person to give you a wet willy.",
    "Who was your first celebrity crush?",
    "Do the salt and ice challenge.",
    "Do you believe in any superstitions?",
    "Lick your big toe.",
    "Have you showered today?",
    "Open the closest book to a random page, point at a random sentence, and then text that sentence to the last person that texted you without giving any other context.",
    "Where’s the farthest you’ve traveled?",
    "Take a deep breath of the socks you are wearing right now.",
    "What’s the weirdest food combo that you eat?",
    "Drink a glass of water while upside down.",
    "What’s the meanest thing you have ever said to someone?",
    "Do 25 sit ups.",
    "What was the last movie that made you cry?",
    "Show the other persons the five most recent photos in your camera roll.",
    "If you had to be stuck on a desert island with any celebrity, who would it be?",
    "Cut some of your hair, even if it is just a small strand.",
    "Have you ever gotten arrested or almost gotten arrested?",
    "What is a common skill (ex. Whistling), that you do not possess?",
    "What would your stripper name be?",
    "Tickle the next person you see who is not playing the game.",
    "Have you ever blamed a fart on somebody else?",
    "Chew a piece of gum with the wrapper still on.",
    "When is the last time you peed in your pants?",
    "Make up a song and sing it.",
    "Would you volunteer as tribute for anyone in the Hunger Games?",
    "Eat a tablespoon of butter.",
    "Who is your least favorite person in the room?",
    "Put on makeup without looking in a mirror.",
    "If you were famous, what would it be for?",
    "Do the splits, or go down as far as you can if you can’t do a full split.",
    "What is your biggest insecurity?",
    "Lick the elbow of the person beside you",
    "Have you ever eaten your own boogers?",
    "Let another person post something on one of your social media accounts.",
    "What is the meanest practical joke you have ever pulled on someone?",
    "Do the worm.",
    "Who was the last person you betrayed?",
    "Dance to your favorite song, in its entirety, in your driveway.",
    "What is the last thing you searched for on your phone?",
    "Close your eyes and have another person place your finger on a part of their body, then guess what part you are touching.",
    "What’s the stupidest thing you were scared of as a kid?",
    "Lick your own armpit.",
    "Do you sing in the shower?",
    "Trade one article of clothing with another person for the next 2 rounds.",
    "Do you cheat at board games?",
    "Do jumping jacks until it is your turn again.",
    "What is your least favorite feature?",
    "Give the person to your left a foot rub.",
    "Have you ever sung karaoke?",
    "Allow the other persons to send one text to anyone in your contact list.",
    "Who is your least favorite family member?",
    "Passionately makeup with the palm of your hand.",
    "Have you ever lied on your resume?",
    "Take off your socks using only your teeth.",
    "Do you ever intentionally smell your own farts?",
    "Eat a small portion of toothpaste.",
    "Have you ever pretended to not get a text to get out of doing something?",
    "Lick a bar of soap.",
    "What is the worst thing you have ever smelled?",
    "Eat a piece of toilet paper.",
    "Have you ever pretend to cry to get out of a speeding ticket?",
    "Sing the alphabet backwards, every time you mess up another person is allowed to pinch you.",
    "What is the craziest dream you can remember having?",
    "Drink a mystery cocktail created by the other persons.",
    "What is an instant deal breaker in a new relationship?",
    "Try to sing a song with a mouthful of water.",
    "Have you ever performed in front of a crowd?",
    "Play the next 3 rounds blindfolded.",
    "What is your biggest regret in life?",
    "Do your best yodel.",
    "Do you have any hidden talents?",
    "Go commando for the next 5 rounds.",
    "Have you ever been in a fight?",
    "Put an ice cube down your pants and let it melt.",
    "Do you walk around naked when you are home alone?",
    "Roast everybody that is playing the game.",
    "What is the worst date you’ve ever been on?",
    "Do your best acceptance speech for an award of your choice.",
    "Do you believe in love at first sight?",
    "Stick your hand in the toilet bowl for 3 seconds.",
    "Where is the craziest place you have ever had sex?",
    "Eat a booger.",
    "What is the dumbest thing you have done while drunk?",
    "Lick the ear of the person across from you.",
    "What’s the most inappropriate time you have ever laughed?",
    "Call Subway or a local sub shop and ask how long their foot long sub is.",
    "Have you ever won an award you didn’t deserve?",
    "Take a bite out of a stick of chapstick or lipstick.",
    "Have you ever shoplifted?",
    "Only speak using song lyrics for the next 3 rounds.",
    "Have you ever had sex in your parents’ bed?",
    "Take a shot of lime juice.",
    "What is the worst place you have ever thrown up?",
    "Eat a piece of fruit off of the stomach of the person to your right.",
    "What is your worst habit?",
    "Wear your underwear on the outside of your clothes for the next ten minutes.",
    "What would your dream job be?",
    "Do your best Michael Jackson impersonation.",
    "Are there any movies that are widely accepted as bad, but you love? If so which ones?",
    "Put peanut butter between your toes and let a dog lick it off, or sit with it there for the next 4 rounds if no dog is nearby.",
    "Would you ever date someone much older than you?",
    "Play imaginary limbo. How low can you go?",
    "Have you ever cheated on someone?",
    "Let the other persons give you a makeover, using condiments as makeup.",
    "Have you ever eaten food that’s been on the floor longer than 5 seconds?",
    "Eat a banana and then chug a can of sprite.",
    "Tell the other persons your best pickup line.",
    "Finish another person’s drink.",
    "What is your favorite possession?",
    "Allow another person to “mama bird” a piece of food, to you, the “baby bird”.",
    "What is the dumbest thing you have ever lied about?",
    "Shave off one of your eyebrows.",
    "When was the last time you watched an “adult movie”?",
    "Draw a face on your stomach and talk using your stomach face for the next 5 rounds.",
    "What is the worst thing you have ever tasted?",
    "Play the next 3 rounds with a slice of onion underneath both of your eyes.",
    "What is the worst type of music?",
    "Make the ugliest face you can make.",
    "Which celebrity do you hate the most?",
    "Let another person rock you like a baby.",
    "Have you ever intentionally sabotaged a coworker?",
    "Chug a glass of milk.",
    "What do you think happens when you die?",
    "Put your finger in your ear and then lick your finger.",
    "What is your biggest guilty pleasure song/ artist?",
    "Take off another person’s sock without using your hands.",
    "Which is worse, physical pain or emotional pain?",
    "Allow the other persons to blindfold you. And then guess who each person is just by sniffing them.",
    "Who is the biggest flirt in the room?",
    "Dance like a ballerina for 2 minutes.",
    "Would you ever get plastic surgery?",
    "Sit with a wet sponge on your head for the next 5 rounds.",
    "What is your least favorite sport to play?",
    "Bite another person’s fingernails.",
    "Who was the last person you said “I love you” to?",
    "Take a shower with your clothes on.",
    "Where do you want to travel to the most?",
    "Put as many marshmallows in your mouth as you can.",
    "Have you ever paid for sex?",
    "Let your dog lick you on the mouth.",
    "Do you still know your first crush?",
    "Give the person to your right a piggy back ride around the room.",
    "What word do you hate the most?",
    "Skip backwards in a circle while saying a tongue twister.",
    "What is the worst rumor you’ve ever started or participated in?",
    "Eat a banana with the peel on.",
    "If you could switch bodies with anyone in the world, who would it be?",
    "Wear your pants backwards for the next 3 rounds.",
    "Would you ever consider being a nudist?",
    "Allow the other persons to do your eyebrows.",
    "Do you believe in soul mates?",
    "Eat a piece of dog food and try to convince the other persons it’s delicious.",
    "What is the most expensive gift you have ever bought someone?",
    "Lick another person’s palm.",
    "Have you ever been fired from a job?",
    "Pretend like you are embarrassed for other people to see your thumbs.",
    "Would you rather become an astronaut or movie star?",
    "Let another person draw something on your face.",
    "Who is your hero?",
    "Hula hoop for 2 minutes.",
    "Who did you have your best kiss with?",
    "Communicate only by whistling for the next 5 minutes.",
    "Has a Pixar movie ever made you cry?",
    "Give yourself a scalp massage using vegetable oil.",
    "Would you marry someone you didn’t love if they were really rich?",
    "Make a sandwich, blindfolded.",
    "Without saying who, do you want to kiss any of the other persons?",
    "Chew on a piece of tape for the remainder of the round.",
    "Are you more likely to be 10 minutes late or 10 minutes early?",
    "Call your mom and tell her you got engaged.",
    "Have you ever been on TV?",
    "Stand on one leg for 10 minutes.",
    "Do you think you could go a month without using the internet?",
    "Moonwalk down the street in front of your house.",
    "What’s something you wish you were better at?",
    "Ask your neighbor if they’ve seen your missing tractor, imply that they stole it.",
    "Have you ever had a near-death experience?",
    "Peel a potato with your teeth.",
    "Do you think cheating is ever justified?",
    "Lick another person’s toes.",
    "Have you ever compromised your morals for money?",
    "Smell all the other persons’ breath and rate it 1-10.",
    "Do you pee in the shower?",
    "Talk like Shakespeare for the next 3 rounds.",
    "When was the last time you turned your phone completely off?",
    "Eat a spoonful of cinnamon.",
    "Has a book ever made you cry?",
    "Get a stranger to smell your breath.",
    "What do you think would be the worst way to die?",
    "Eat a leaf.",
    "What is the worst movie you have ever seen?",
    "Wear a necklace made out of floss, which another person has just used, for the next 5 rounds.",
    "Have you ever started a fire while cooking?",
    "Smell all of the other persons’ feet.",
    "Have you ever seriously injured another person?",
    "Do a wall sit for 60 seconds.",
    "What is the worst pain you’ve ever experienced?",
    "Chew on a piece of tin foil for 30 seconds.",
    "How many people have you slept with?",
    "Prank call the last person that called you.",
    "What is the most charitable or heroic thing you have done?",
    "Put your finger in another person’s nose.",
    "How do you think other people perceive you?",
    "Tie your hands to your ankles and stay like that for the next 4 rounds.",
    "Which person made the worst first impression on you?",
    "Eat a clove of garlic.",
    "What is the craziest thing you would do sexually?",
    "Take a shot of toilet water.",
    "What is the nastiest smell that you love?",
    "Put a pillow under your shirt and pretend to be going into labor.",
    "Have you ever compromised your beliefs for a significant other?",
    "Lick the floor.",
    "Do you believe in fate?",
    "Smell another person’s armpit.",
    "Would you rather be forgotten when you die, or live forever in infamy?",
    "Hug a stranger and don’t let go for five seconds.",
    "What animal best represents you?",
    "Seduce a stuffed animal.",
    "What is the most scared you have ever been?",
    "Let the other persons wrap you up in toilet paper and stay like that for the rest of the game.",
    "If you could tattoo clothes on you and be naked forever, would you?",
    "Let another person lick chocolate syrup off of your stomach.",
    "What is the dumbest trend you have ever gone along with?",
    "Eat a raw onion.",
    "Did you have an imaginary friend as a child?",
    "Shave a strip of hair from your arm.",
    "Do you believe in astrology?",
    "Cut another person’s toenails.",
    "Have you ever thrown up on a roller coaster?",
    "Post a picture of your toilet on social media, with a “deep” quote as the caption.",
    "What is the longest distance you have ever run?",
    "Walk like a crab for 3 minutes.",
    "What do you think is the most important lesson to teach your kids?",
    "llow another person to slap you in the face.",
    "Have you ever done the deed at work?",
    "Suck on your thumb for the next 3 rounds.",
    "What is the best advice you have ever received?",
    "Try to kick yourself in the face.",
    "What is the worst hair style you’ve had?",
    "Eat a piece of food without using your hands.",
    "Do you believe in karma?",
    "Get hyped up like a wrestler before a fight and rip off your shirt.",
    "Have you ever had a paranormal experience?",
    "Place both your hands in another persons pockets and keep them there for 15 minutes. You must each perform a dare before you are allowed to remove them.",
    "Have you ever had sex in a public place?",
    "Lick a dollar bill.",
    "Which person do you trust the least?",
    "Imitate a monkey AND a donkey at the same time",
    "Have you ever said “I love you” and not meant it?",
    "Wear a beard made of shaving cream for the next 3 rounds.",
    "If you could slap another person, who would it be?",
    "Brush another person’s teeth using your index finger.",
    "What is the worst advice you have ever received?",
    "Go outside and take a selfie with a stranger.",
    "What misconception do people have about you?",
    "Send your significant other a text that says “I know what you did last summer”.",
    "Do you believe there is alien life?",
    "Wink and lick your lips whenever someone new walks in the room.",
    "Have you ever gotten blackout drunk?",
    "Take a bite out of a crayon.",
    "What was your weirdest habit as a kid?",
    "Send a text using only your tongue, don’t proofread it before sending.",
    "Who would you help hide a body for?",
    "Reenact your favorite movie scene.",
    "Have you ever given bad advice on purpose?",
    "Pull out 5 strands of leg hair.",
    "Do you tell a friend if they have something in their teeth?",
    "Do your best burlesque routine for 1 minute.",
    "If you could only eat one food for the rest of your life, what would it be?",
    "Try to make yourself cry.",
    "Have you ever had lice?",
    "Give yourself a brain freeze.",
    "Do you like being alone or surrounded by friends?",
    "For the next five rounds, any time a person says “cheese”, spank yourself.",
    "Would you rather have 4 kids or no kids?",
    "Wear your pants on your arms for the rest of the game.",
    "Are you a sore loser?",
    "Spin around 15 times and then jump rope for 30 seconds.",
    "Do you look at your poop before you flush the toilet?",
    "Wear your socks on your hands for the next 5 rounds.",
    "What is more important to you, revenge or forgiveness?",
    "Call a random number and confess your love for the person on the end.",
    "Have you ever gone skinny dipping?",
    "Sing and dance to YMCA without any music.",
    "Which person do you trust the most?",
    "Tell the most offensive joke you know.",
    "Do you believe in ghosts?",
    "Call a random number and ask them how their day was, keep them on the line for as long as possible.",
    "What are you most proud of in life?",
    "Take a whiff of ground pepper and try not to sneeze.",
    "What is your least favorite memory from high school?",
    "Take an embarrassing selfie and set it as your profile picture on one of your social media accounts for the rest of the night.",
    "What song can you not help but dance to?",
    "Sit on another person’s lap until the next round.",
    "Have you ever smoked marijuana?",
    "Lick the cheek of the person to your left.",
    "What is the pettiest thing you have ever done?",
    "Take a shot of mustard.",
    "When was the last time you stalked an ex on social media?",
    "Try to put your foot behind your head.",
    "What is your biggest pet peeve?",
    "Glue 2 fingers together and leave them like that for the rest of the game.",
    "What is a useless skill that you would like to learn?",
    "Freestyle rap for a minute.",
    "What is one job that you could never do?",
    "Have you ever had an embarrassing dream about one of the other persons?",
    "If you could be a fly on the wall, where would you fly?",
    "Let the other persons paint your nails.",
    "What is the worst injury you’ve ever had?",
    "Put cotton balls in your ears for the next 3 rounds.",
    "If you could only eat one candy for the rest of your life, what would it be?",
    "Do your best tango with the nearest mop or broom.",
    "When was the last time you picked your nose?",
    "For the next 5 minutes, only respond to people by saying “you know that’s right”.",
    "Are you scared of getting old?",
    "Sit in the nearest closet until it is your turn again.",
    "Who has the best butt in the room?",
    "Do a back bend.",
    "What is something you feel guilty about?",
    "Kiss another person on the cheek.",
    "What is the sexiest thing someone can do?",
    "Talk with a Russian accent for the next 3 rounds.",
    "Do you have a crush on any of your coworkers?",
    "Do the chicken dance until it is your turn again.",
    "Do you still love any of your exes?",
    "Let another person spank you with a fly swatter.",
    "Have you ever ghosted somebody?",
    "Paint your eyebrows using peanut butter.",
    "Have you ever had a one night stand?",
    "Eat a spoonful of soy sauce.",
    "What is the scariest thing you’ve ever done?",
    "Call a random person and sing a song, don’t stop until they hang up.",
    "Would you eat human meat grown in a lab?",
    "Stand on one leg for the next 2 rounds.",
    "What was your nickname as a child?",
    "Eat a raw egg.",
    "What is the worst present anyone has given you?",
    "Have you ever had a crush on a friend’s boyfriend/girlfriend?",
    "If you had to make out with a boy at school, who would it be?",
    "Would you rather go for a month without washing your hair or go for a day without wearing a bra?",
    "Have you ever asked someone out?",
    "What size is your bra?",
    "Do you wear tighty whities or granny panties?",
    "Has a crush ever found out you liked them and turned you down?",
    "What’s the most embarrassing thing you’ve done regarding your crush?",
    "What do you do to get yourself 'sexy'?",
    "Would you kiss a guy on the first date? Would you do more than that?",
    "Who are you jealous of?",
    "If someone paid you $1000 to wear your bra outside your shirt, would you do it?",
    "Who would you hate to see naked?",
    "How long have you gone without a shower?",
    "If you could only text one person for the rest of your life, but you could never talk to that person face to face, who would that be?",
    "How long have you gone without brushing your teeth?",
    "What's one thing you would never eat on a first date?",
    "What have you seen that you wish you could unsee?",
    "If you could be reincarnated into anyone's body, who would you want to become?",
    "What's the most useless piece of knowledge you know?",
    "What did you learn in school that you wish you could forget?",
    "Is it better to use shampoo as soap or soap as shampoo?",
    "If you ran out of toilet paper, would you consider wiping with the empty roll?",
    "What would be the worst part about getting pantsed in front of your crush?",
    "What's the best thing to say to your friend that would be the worst thing to say to your crush?",
    "Would you rather eat dog food or cat food?",
    "If you had nine lives, what would you do that you wouldn't do now?",
    "If you could play a prank on anyone without getting caught, who would you play it on?",
    "Have you ever pretended to like a gift? How did you pretend?",
    "Would you rather not shower for a month, or eat the same meal every day for a month?",
    "f you could choose to never sweat for the rest of your life or never have to use the bathroom, which would you choose?",
    "Describe what your crush looks like.",
    "Is there anything about your life you would change?",
    "How many people have you kissed?",
    "What's your biggest turn-on?",
    "You have to delete every app on your except for five. Name the five you would keep.",
    "Have you ever sent out a nude Snapchat?",
    "Have you ever received a nude selfie? Who was it from?",
    "Have you ever had a crush on a teacher?",
    "Have you ever sent someone the wrong text?",
    "If you had to choose between dating someone ugly who was good in bed or dating someone hot who was bad in bed, which would you choose?",
    "If you could be invisible, who would you spy on?",
    "f you could date one of your bro's girlfriends, who would it be?",
    "What your favorite body part?",
    "When was the last time you flexed in the mirror?",
    "Have you ever been in love?",
    "What turns you on the most?",
    "If your parents hated your girlfriend, would you dump her?",
    "If your girlfriend hated your best friend, what would you do?",
    "Have you ever been rejected by someone?",
    "If you had to choose between being poor and smart or being rich and dumb, what would you choose?",
    "What have you lied to your partner about?",
    "Have you ever cheated on your partner?",
    "Would you go out with an older woman?",
    "When was the last time you cried?",
    "Have you ever fallen in love at first sight?",
    "What would you do if you found out your girlfriend liked someone else?",
    "Who do you want to make out with the most?",
    "If you had to flash just one person in this room, who would it be?",
    "Who has the best smile?",
    "How about prettiest eyes?",
    "Have you ever smoked?",
    "Have you ever tried drugs?",
    "Would you go to a nude beach?",
    "Are you still a virgin?",
    "Do you have hidden piercings or tattoos?",
    "How long was your longest relationship?",
    "If you could have one celebrity follow you on Instagram, who would that be?",
    "Do you want to have kids? How many?",
    "Would you ever get into a long-distance relationship?",
    "Describe the person of your dreams.",
    "If you're girlfriend or boyfriend broke up with you at school, what would you do?",
    "Basketball, baseball, or football?",
    "What was your first job?",
    "What are you most excited about?",
    "Have you ever failed a class?",
    "What was a rumor that went around about you?",
    "Have you ever cheated on a test?",
    "Have you ever sexted anyone?",
    "Have you ever been to a nudist beach? Would you consider going?",
    "Would you ever consider posing for Playboy?",
    "Who has seen you without clothes on?",
    "Have you ever seen a naughty magazine?",
    "Have you ever sent a nude selfie? Who would you send it to?",
    "Have you ever searched for something dirty on the internet?",
    "Who do you most want to sleep with, out of everyone here?",
    "What's your favorite body part on your partner?",
    "Have you ever been attracted to the same sex?",
    "When did you lose your virginity, and to whom did you lose it?",
    "What's your ultimate sexual fantasy?",
    "Would you go out with an older guy? How old is too old?",
    "Do you sleep in the nude?",
    "How much money would we have to pay you for you to agree to flash your boobs?",
    "Have you ever been in a 'friends with benefits' situation?",
    "If you had to go skinny dipping with someone, who would you choose?",
    "If I paid you $100, would you wear your sexiest clothes to class?",
    "Let the group choose an item for you to brush your teeth with.",
    "Write your name on the floor with your tongue.",
    "Go outside and pick exactly 40 blades of grass with a pair of tweezers.",
    "Stick a Hot Cheeto in your nose and leave it there for 5 minutes.",
    "Open Facebook, go to the account of the first person you see, and like every post on their wall going back to a year.",
    "Eat a whole piece of paper.",
    "Lick a car tire.",
    "Open your front door and howl like a wolf for 30 seconds.",
    "Let the person to your right put duct tape on any part of your body they choose and rip it off.",
    "I dare you to tie your hands to your ankles for the rest of the game.",
    "Put a bunch of honey on your nose and coat it with flour",
    "Dump a bunch of legos on the floor and walk over it with your bare feet.",
    "Eat a spoonful of mustard.",
    "Jump into a dumpster.",
    "Lift up the couch cushions, and if there is anything under it, you need to put it in your mouth for 10 seconds.",
    "Spin around 10 times and try to walk straight.",
    "Eat a raw egg.",
    "Write a letter to your doctor describing an embarrassing rash you have, and post it on Facebook.",
    "Cover your hair with shaving cream and leave it on until the end of the game.",
    "Let the group choose 3 random things from the refrigerator and mix it together. Then you have to eat it.",
    "Stand up and do jumping jacks until your next turn.",
    "Rub your armpits and then smell your fingers.",
    "Dig through the trash and name everything you find.",
    "Sniff another person’s armpit for 10 seconds.",
    "Give your phone to another person to send a text message to their contact of choice.",
    "Let the other persons go through your phone for a minute.",
    "Allow someone to pour ice down your shirt and pants.",
    "Let another person throw flour in your face.",
    "Sing a song chosen by the group while eating spoonfuls of peanut butter.",
    "Close your eyes and let your friends put whatever food from the fridge they want in your mouth.",
    "One by one, make up a title for each persons’ movie about their life.",
    "Let your friends pose you and stay like that until the next round.",
    "Let each person choose one word, then attempt to form a sentence with it and post it to Facebook.",
    "Empty your purse, backpack, or wallet and let everyone see what you have.",
    "Allow the person to your right to tickle you.",
    "Whoever’s name begins with an A in the group must call your parents and tell them what a bad friend you are to them.",
    "Let each person in the group slap you as hard as they can on your butt.",
    "Do your best impression of someone in the room and keep going until someone correctly guesses who it is.",
    "Eat a raw onion and do your best not to cry.",
    "Be blindfolded and let someone feed you something.",
    "Lick mayonnaise off of someone’s toe.",
    "Someone has to dip their finger in the trash can and you have to lick it.",
    "Go to the bathroom, and the person to your left has to be in there with you the whole time.",
    "Trade socks with the person to your right.",
    "Have the person to your right do 10 squats while you lie underneath them.",
    "Let a person in the group put a leash on you and walk you down the street.",
    "Hold hands with the person to you left for the rest of the game.",
    "Hand your phone to the person across from you and let them post whatever they want to your social media accounts.",
    "Smells someone else’s shoes",
    "Take the socks off the person’s feet across from you and wear them like gloves until your next turn.",
    "Serenade the person next to you.",
    "Take a selfie with the person next to you, and post it on social media along with a deep and emotional paragraph about what they mean to you.",
    "Let the person across from you give you a wedgie.",
    "Dance aggressively until you run out of breath.",
    "Eat a single spaghetti like in Lady and the Tramp with the person to your left.",
    "Get a bar of soap from the bathroom and sell it to the group for 3 minutes.",
    "Go outside, and while skipping down the street, sing “Let it Go’ from Frozen.",
    "With your eyes closed, pick someone from your contact list and send them a text.",
    "Stand up and do your best impersonation of the person on your right.",
    "Go in the kitchen and rearrange everything in the food pantry in alphabetical order.",
    "Imagine the person to your left is your pet, talk to them as though you just got home.",
    "Imagine that you are a dog and act like it until your next turn.",
    "Describe what the sky looks like without using the words blue or white.",
    "Sing the chorus of your favorite song.",
    "Everytime someone chooses dare, walk across the floor like a crab and embrace them with a hug.",
    "Make up a song about the host of the party.",
    "Knock on the neighbor’s door and explain to them that your pet penguin got loose and ask if you can look for it in their backyard.",
    "Invent a new color for nail polish and describe the person who would be most likely to wear it.",
    "For the next 15 minutes, everything you say must be spoken in baby talk.",
    "Give 5 dollars to each person if you curse at any point during the game.",
    "Make a sandwich while blindfolded.",
    "Stick an egg in the microwave and attempt to juggle it for 30 seconds.",
    "Eat a spoonful of hot sauce.",
    "From now until your next turn, every time someone talks, interrupt by saying, “that’s a lie.”",
    "You notice that the person sitting on your right has something on their face, spit on your finger and wipe it off for them.",
    "Get down on one knee and propose to the person on your left.",
    "Awkwardly smell someone else’s hair until they notice.",
    "Take the socks off the person’s feet across from you and wear them like gloves until your next turn.",
    "Open Facebook and “like” the first thing that pops up even if you disagree with it.",
    "Stand up and do your best impersonation of your mom.",
    "Go for a short walk outside and while walking, hold a conversation with yourself.",
    "Rearrange all the pictures in the room according to their size.",
    "Take off your shoe and clean your foot as though you are an animal.",
    "Stick your head in the toilet.",
    "Put makeup on the person sitting the farthest away from you.",
    "Do your best impersonation of someone else in the room and keep going until someone else guesses who you are.",
    "Call a realtor and show genuine interest in a random house for several minutes.",
    "For the next 10 minutes, when someone speaks, put your ear up close to them and act as though you can’t hear what they are saying.",
    "Stand up and do jumping jacks until your next turn.",
    "For the rest of the game, you must cluck like a chicken at the beginning and end of everything you say.",
    "Be silent and say nothing from now until your next turn.",
    "While blindfolded, you must eat something that the person to your left chooses to feed you.",
    "Tie your shoe strings together with another person and walk together to the end of the driveway and back.",
    "Stand in the backyard and yell at the top of your lungs, “I was adopted! Nooooooo.”",
    "Text a friend and tell them their hair is on backward.",
    "Wear your clothes backward for the duration of the game.",
    "Tell someone something negative you have said about them in private.",
    "Go outside to the trash bin and throw a tantrum because someone put trash in it.",
    "Go outside and pick exactly 40 blades of grass with a pair of tweezers.",
    "Call someone and confess your new-found love for Justin Bieber.",
    "Kiss the person to your right on the cheek.",
    "Sniff the person to your left and tell them they smell bad.",
    "Rub your armpits and then smell your fingers.",
    "Sit on your hands for the remainder of the game.",
    "Knock on the neighbor’s door and ask if you can park your helicopter in their driveway.",
    "Take someone with you outside in the sight of the neighbors and stare into the sky until someone asks you what you are looking at, then tell them that you saw a UFO.",
    "Text your mom and tell her that you are expecting a baby.",
    "Walk outside frantically carrying an empty leash and approach people asking them if they have seen your pet alligator because it just escaped.",
    "Go into the bathroom and look in the cabinet. Write a short summary of what you find and read it to the group.",
    "Call the nearest gas station and ask them if they sell hemorrhoid cream.",
    "Stop a car that is going down the street and tell them that their wheels are turning.",
    "Make a sandwich containing every condiment in your refrigerator.",
    "Close your eyes and let everyone draw on you for 5 minutes.",
    "Tell a bizarre 2-minute story about the night you slept in the woods.",
    "Stand up and dance the twist until your next turn.",
    "Name the person in the room who you think is the best dressed.",
    "Name the person in the room who you think is the worst dressed.",
    "Text your siblings and tell them that you just found out you are adopted.",
    "Make the sound of a dripping faucet until your next turn.",
    "From now until the end of the game, every time you talk, speak like a robot.",
    "Act like a cheerleader and do a cheer about the host of the party.",
    "For the rest of the game, you must only communicate using animal sounds.",
    "Make confetti out of a tissue.",
    "Describe to the group what your last bathroom experience was like.",
    "Get a magazine and go outside. Roll up the magazine, put it on your nose and act and sound like an elephant.",
    "Make a hat out of aluminum foil then put the hat on and post a selfie to social media. Leave the hat on for the duration of the game.",
    "Hang your socks from your ears until the end of the game.",
    "Fill your mouth with water and act like a fountain.",
    "For the rest of the game you must say your name at the beginning and the end of every sentence you speak.",
    "Repeat everything the person to your left says until your next turn.",
    "Choose one inanimate object that is in the room. Now spend the next 2-minutes telling the group what that object is thinking.",
    "Attempt to lick your elbow for at least five minutes.",
    "Make eye contact with a person and don’t break it until it’s your turn again.",
    "Get a mouthful of water and gargle it until your next turn.",
    "Do the chicken dance to no music until your next turn.",
    "Crack an egg on your head.",
    "Stick out your tongue and talk that way until your next turn.",
    "Bust your best dance move right now.",
    "Turn your pants inside out and wear them.",
    "Do everything with “crab hands” for the rest of the game.",
    "Reenact what you think it is like to give birth.",
    "For the rest of the game, speak like you are the President of America.",
    "Pretend like you are drunk for the rest of the game.",
    "Eat a spoonful of hot sauce.",
    "Make up a short cheer and shout it to the room.",
    "Speak in the voice of your favorite cartoon character until your next turn.",
    "Use ketchup to put the mark of Simba on your forehead.",
    "Put a piece of American cheese on your cheek and leave it until your next turn.",
]


@app.route('/get/<string:name>')
def hello(name):
    if name == 'truth':
        rnd = random.randint(0, truth.__len__())
        return jsonify({'responce': truth[rnd]})
    elif name == 'dare':
        rnd = random.randint(0, dare.__len__())
        return jsonify({'responce': dare[rnd]})
    elif name == 'truthordare':
        rnd = random.randint(0, truthordare.__len__())
    else:
        return jsonify({'responce': "Error in path"})
    


app.run(debug=True, host='0.0.0.0', port=8080)
